# Generated by Django 4.1 on 2022-11-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0002_alter_movie_actors_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
